# Первый список (из предыдущего сообщения пользователя, сохраненный в CSV)
old_links = [
    "https://t.me/shp_logistic",
    "https://t.me/logistika_072",
    "https://t.me/yukbor11",
    "https://t.me/yuk_markazi_pitaklar",
    "https://t.me/Isuzugayk",
    "https://t.me/yuk_xizmati1",
    "https://t.me/zakasmuzikkkk",
    "https://t.me/yuk_baza",
    "https://t.me/xalqaroyuklar",
    "https://t.me/gruzov24na7",
    "https://t.me/logistika_sng_ru_mira_evro_azia",
    "https://t.me/ORDERTRUCK_uzb",
    "https://t.me/Nalichka123",
    "https://t.me/emirfrigo",
    "https://t.me/dalneboyuzsng",
    "https://t.me/Uz_7771",
    "https://t.me/asiyaeurologistics",
    "https://t.me/yuklar_uzb",
    "https://t.me/asiyaeurologistics",
    "https://t.me/Logistika_yuklar",
    "https://t.me/Yuktashish2021",
    "https://t.me/gruzoperivozka_azia",
    "https://t.me/yukfuragabor_FargonaToshkent",
    "https://t.me/yukmarkazilogist",
    "https://t.me/logistik_markazz",
    "https://t.me/logistika_sng1",
    "https://t.me/isuzuuuuuuuuuuuuuuuuuuu",
    "https://t.me/logistika_mezhdunarodnyye",
    "https://t.me/pitak_markazi",
    "https://t.me/vodiy_yuk_markazi",
    "https://t.me/rucargoru",
    "https://t.me/Gruzaperevozki_po_miru",
    "https://t.me/logistikauzru",
    "https://t.me/thesecretlogistics",
    "https://t.me/isizu_yuk_markazi_buxoro_vodiy",
    "https://t.me/Oltiariq_Ref_Yuk_Markazi",
    "https://t.me/gruz_ki",
    "https://t.me/Isuzu_yuk_markazi_buxoro_pitak",
    "https://t.me/LOGISTWAR",
    "https://t.me/rossiya_gruzoperivozka",
    "https://t.me/isuzuskdkdid",
    "https://t.me/tonarsomasval",
    "https://t.me/toshkent_namangan_yuk_markazi",
    "https://t.me/yuktashishxizmatlari",
    "https://t.me/YUKmarkazi360",
    "https://t.me/USLUGALOGISTIKA",
    "https://t.me/isuziyuk",
    "https://t.me/qazaqtransit",
    "https://t.me/gruzestTurUZB",
    "https://t.me/yuk_bor",
    "https://t.me/bekavto_uz",
    "https://t.me/yuk_markazii",
    "https://t.me/LAND_GRUZER",
    "https://t.me/perevozki164",
    "https://t.me/Lklml",
    "https://t.me/TENTOFKA_FURA",
    "https://t.me/qoqon_yuk",
    "https://t.me/yukbor7",
    "https://t.me/furauzbb",
    "https://t.me/KANTENRVOZCHILAR",
    "https://t.me/intlogistika",
    "https://t.me/perevozkipouzb",
    "https://t.me/gruzoperevozkilogistics",
    "https://t.me/asia_logistic",
    "https://t.me/turkiyenakliye",
    "https://t.me/aptekaproff_ru_chat",
    "https://t.me/oltiariq_yuk_tranc",
    "https://t.me/miruzperevozka",
    "https://t.me/uzb_taxsi",
    "https://t.me/Uzbekiston_buylab",
    "https://t.me/uzbekiston_shafyorlari",
    "https://t.me/gruz2020indira",
    "https://t.me/Xalqaro_logistika",
    "https://t.me/lardi_ge",
    "https://t.me/Katta_uzbek_trakti_yuk_markazi",
    "https://t.me/GruzovieperevozkipoUzbekistanu",
    "https://t.me/uzbeklogistika",
    "https://t.me/tonnakilometrdollar",
    "https://t.me/Xorazm_yukmarkazi",
    "https://t.me/gruzytutRF",
    "https://t.me/logistikaua",
    "https://t.me/logistika11",
    "https://t.me/transra",
    "https://t.me/gruzoperevozku_ru",
    "https://t.me/yukmarkazibuxoro",
    "https://t.me/logisticscentre",
    "https://t.me/grt12buiop",
    "https://t.me/logistika_aziya",
    "https://t.me/Salamovtransgroup",
    "https://t.me/gruz_by",
    "https://t.me/worldtransit_chat",
]

# Второй список (из нового сообщения пользователя — в каких он уже состоит)
new_links = """
https://t.me/artemibratva
https://t.me/Kazsng
https://t.me/logitgroup24
https://t.me/gryzovik
https://t.me/Super_Group_Ati_su
https://t.me/perevozka_uzb_rf1
https://t.me/uzbekistonboylabyukla
https://t.me/isuzigrupa
https://t.me/turklogist
https://t.me/UZ_RUS_XALQARO_YUKLARI
https://t.me/gruzoperevozki_po_sng1
https://t.me/logistikasn
https://t.me/milyukkar
https://t.me/trucking1
https://t.me/logisticscargo
https://t.me/gruzperevozkargo
https://t.me/uzbekiston_2022
https://t.me/yuk_yukla_markazi_pitak_Isuzu_uz
https://t.me/poputno_gruz
https://t.me/yuk_markaz_gruz
https://t.me/TiRpark_logistika1
https://t.me/rossia1_2
https://t.me/lognumber1
https://t.me/VODIY_BOYLAB_YUKLAR
https://t.me/perevozka_gruzov_logistika_kz
https://t.me/YUKmarkazi_yuklar_shopirlar
https://t.me/Yuk_Markazi_Fura_Isuzu
https://t.me/Yuk_markazi_gruppa_Vodiy
https://t.me/jizzaxyukmarkazi25
https://t.me/cargo_gruz
https://t.me/logika86
https://t.me/Yuk_markazi_yuk_yukla4432
https://t.me/Yukbor_uzbtrans
https://t.me/UZB_TURK_LOGISTIKA_YUKMARKAZI
https://t.me/gruzoperevozmir
https://t.me/logistika_azia
https://t.me/Yuk_markazi_isuzu_uz
https://t.me/yukmarkazi_furalar
https://t.me/uzbekistonboylabyuklar
https://t.me/mmshlogisticlux
https://t.me/yuk95
https://t.me/namangan_toshkent_yuk_markazi
https://t.me/logisticpost
https://t.me/vertex_global_logistics
https://t.me/yuklogistik4432
https://t.me/logistic_truck
https://t.me/LOGISTIKA_UZBEKISTANA
https://t.me/DUNYO_BOYLAB_YUKLAR
https://t.me/XALQARO_YUKLARI
https://t.me/Russian_logistics
https://t.me/worldlogistic
https://t.me/yuk_markazi_yuk_uz
https://t.me/Yuk_markazi_yuk_yukla
https://t.me/TIRPARK_logistika_yukmarkazi
https://t.me/YUKmarkazi_isuzi_yuklar
https://t.me/YUKMARKZIMEGA
https://t.me/logistics_avto
https://t.me/logisticsRF_SNG
https://t.me/EurAsiaGruz
https://t.me/logistikaN1
https://t.me/mejdunarodni_yukgurpa
https://t.me/AzerbaijanLogistics
https://t.me/bbmpy
https://t.me/akum_tashkent
https://t.me/mycargo
https://t.me/yuk_bor_uzz
https://t.me/Logistika_super_UZB
https://t.me/avtoperevozki
https://t.me/gruzonuz
https://t.me/logistika_1
https://t.me/shafiyorlar
https://t.me/dispetcheruzchanel
https://t.me/OOLIONGROUP
https://t.me/logistika_ru
https://t.me/ROSSIYA_UZB_YUKLAR
https://t.me/Transportationuz
https://t.me/specgruz_express
https://t.me/LOGISTIKA_24
https://t.me/perevozkinss
https://t.me/gruzoperevozochki
https://t.me/PEREVOZKAuzKGruKZ
https://t.me/olottransport
https://t.me/ileritranscomrussia
https://t.me/yuk_uz_24
https://t.me/logistika_uzbb
https://t.me/dalnoboy44
https://t.me/dalnoboichat
https://t.me/uygun_yukler
https://t.me/m_logistik
https://t.me/Pervozka
https://t.me/S_N_G_RUS_GRUZ
https://t.me/dellakz
https://t.me/GSR_Logistics_N1
https://t.me/DalniyboyOltiariq
https://t.me/UZB_RUS_TURK_LOGISTIKA
https://t.me/GURUZAVOYLAR
https://t.me/yukgruppa_dunyo
https://t.me/Russiasng
https://t.me/transatlas
https://t.me/KirAdeNlogistics
https://t.me/yuk_markazi_pitak_uz
https://t.me/isuzuchilar_uzb
https://t.me/Yuk_Markaazi
https://t.me/YUK_SENTR
https://t.me/intercargouzz
https://t.me/Logistikagroup
https://t.me/logistics_chat
https://t.me/TvoiGruz
https://t.me/cac_service
https://t.me/yukboruzb
https://t.me/chempionlogistic
https://t.me/Mir_Logistika_No1
https://t.me/yuk_markazi_pitaklar
https://t.me/ANDIJON_ISUZU_Yuk_markazi
https://t.me/worldlogist
https://t.me/logisticarsi
https://t.me/logistika_777
https://t.me/YANDEX_GRUZ_YUKMARKAZI_YUKLAR
https://t.me/DOVUDXONisuzu50X026OA
https://t.me/LOGISTICA_UZBEKISTAN
https://t.me/dellauz
https://t.me/uzbekiston_boylab_yuk
https://t.me/gruzoperevozkiRU_choogl
https://t.me/lagovb
https://t.me/yukmarkaziuz_N1
https://t.me/Yuk_Markaz_Furalar
https://t.me/mygruz_ofical_chat
https://t.me/LOGISTICAUZ
https://t.me/globalfreightexchange
https://t.me/yuk_tashish_xizmati7
https://t.me/yukmarkazi2
https://t.me/yuk_tashish_xizmatlari
https://t.me/logisticsystem
https://t.me/LOGISTIKA_SNG
https://t.me/muhammadsaid74
https://t.me/yuk_gruppa
https://t.me/dispetcheruz_yuklar
https://t.me/truckingBY
https://t.me/fargona_toshkent_samarqand_yuk
https://t.me/mirovoy_gruz01
https://t.me/evro_asia_buxara_logistic
https://t.me/YAVEZUGRUPP
https://t.me/cargo_BY
https://t.me/shax_1414
https://t.me/TIRtrans
https://t.me/liderlagist
https://t.me/translogisticspbru
https://t.me/UZBEKISTON_BOYLAB_Fargona
https://t.me/yukmarkazi_2022
https://t.me/friendslogisticians
https://t.me/BarakaYuklari
https://t.me/della_uz
https://t.me/shp_logistic
https://t.me/ffus123
https://t.me/Trak_uz
https://t.me/world_deliver
https://t.me/Yuk_bor_Yuk
https://t.me/Logistics_com
https://t.me/pitak_guripasi_yuk_markazi
https://t.me/logistikasng
https://t.me/optomtovar
""".strip().splitlines()

# Сравнение списков: какие из первого не входят во второй
not_in_new = sorted(set(old_links) - set(new_links))

with open('links.txt', "w", encoding="utf-8") as f:
    for i in not_in_new:
        f.write(i + '\n')
